name: Cycode Scan (OIDC)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  cycode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python for Cycode CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Cycode CLI
        run: |
          pip3 install --upgrade cycode

      - name: Get OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=cycode")
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Set environment variable
        run: export CYCODE_API_URL=https://api.cycode.xyz
             export CYCODE_CLIENT_ID=cycsi-334fd661-6cc9-44b6-b27f-7241df9615ba
             export CYCODE_ID_TOKEN=$TOKEN

      - name: Run scans
        run: |
          cycode status
          cycode --client-id $CYCODE_CLIENT_ID --id-token $TOKEN scan path .
