name: Cycode Scan (OIDC)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  cycode:
    runs-on: ubuntu-latest
    env:
      CYCODE_API_URL: ${{ vars.CYCODE_API_URL }}
      CYCODE_CLIENT_ID: ${{ vars.CYCODE_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python for Cycode CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Cycode CLI
      - name: Install Cycode CLI
        run: |
          pip3 install --upgrade cycode

      # Request OIDC token from GitHub
      - name: Get OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      # Run scans using client id from GitHub variables and OIDC token from previous step
      - name: Run scans
        env:
          CYCODE_ID_TOKEN: ${{ steps.oidc.outputs.token }}
        run: |
          cycode status
          cycode scan path .
