name: Cycode Scan (OIDC)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  cycode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python for Cycode CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Cycode CLI
        run: |
          pip3 install --upgrade cycode

      - name: Get OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=cycode")
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Authenticate
        run: |
          cycode auth oidc --client_id '${{ secrets.CYCODE_CLIENT_ID }}' --id-token '${{ steps.oidc.outputs.token }}'

      - name: Run scans
        run: |
          cycode scan secrets .
          cycode scan sast .
          cycode scan iac .